logsBucket: 'gs://bucket67ut'

steps:
- id: 'terraform init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      if [ "$BRANCH_NAME" = "dev" ]; then
        cd EnvironmentCreation/dev/
      elif [ "$BRANCH_NAME" = "prod" ]; then
        cd EnvironmentCreation/prod/
      fi
      terraform init

- id: 'terraform plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      if [ "$BRANCH_NAME" = "dev" ]; then
        cd EnvironmentCreation/dev/
      elif [ "$BRANCH_NAME" = "prod" ]; then
        cd EnvironmentCreation/prod/
      fi
      terraform plan

- id: 'terraform apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      if [ "$BRANCH_NAME" = "dev" ]; then
        cd EnvironmentCreation/dev/
      elif [ "$BRANCH_NAME" = "prod" ]; then
        cd EnvironmentCreation/prod/
      fi
      terraform apply -auto-approve
